// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6FJqjk9aLUc6IRR6yGoAgUq2jpKl07dc',
    appId: '1:411727287177:web:01e91d39a1555ec38d0758',
    messagingSenderId: '411727287177',
    projectId: 'uitmgo',
    authDomain: 'uitmgo.firebaseapp.com',
    storageBucket: 'uitmgo.appspot.com',
    measurementId: 'G-16WK5PDMW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg5vcqb7hiaxNF5GVrT3bpfODj4mLN73U',
    appId: '1:411727287177:android:3c87de0d6fac5fc28d0758',
    messagingSenderId: '411727287177',
    projectId: 'uitmgo',
    storageBucket: 'uitmgo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfn10H_Dq2U1w3Q0U0xVNohQgQI-mFe18',
    appId: '1:411727287177:ios:b83de2861a2a658b8d0758',
    messagingSenderId: '411727287177',
    projectId: 'uitmgo',
    storageBucket: 'uitmgo.appspot.com',
    androidClientId: '411727287177-081b6ti5bo455s3dsh8an8t6n0gn9ji1.apps.googleusercontent.com',
    iosClientId: '411727287177-g640bbr98q62uk1pb63pe8vo72o8jra6.apps.googleusercontent.com',
    iosBundleId: 'com.example.uitmgo',
  );
}
